server:
  port: 8091
spring:
  data:
    mongodb:
      username: appuser
      password: app123
      host: localhost
      port: 27017
      database: appdb
      authentication-database: appdb
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true